export const SECURITY_FRAMEWORK = {
  domains: [
    { name: 'Identity & Access', color: '#FF63A0', subs: ['IGA','PAM','SSO / Federation','MFA / Passwordless','ITDR','Directory Services','CIAM','Secrets Management','Privileged Remote Access','Password Manager'] },
    { name: 'Cloud & App Security', color: '#FC413D', subs: ['CSPM','CNAPP','CIEM','CWPP','CASB','Container / Kubernetes','SAST','DAST','SCA','WAF','API Security','Secrets Scanning','IaC Security','Cloud Detection & Response'] },
    { name: 'Network & Infrastructure', color: '#60D673', subs: ['NGFW','IDS / IPS','NDR','ZTNA','DNS Security','NAC','Secure Web Gateway','DDoS Protection','Deception','PKI / Cert Management','Micro-segmentation','Remote Access / VPN'] },
    { name: 'Security Operations', color: '#3186FF', subs: ['SIEM','SOAR','Data Pipeline / Log Management','MDR','Threat Intelligence','Threat Hunting','UEBA','Attack Surface Management','VM Scanning','Pen Testing / BAS','IR Platform / Retainer','Digital Forensics','Digital Risk Protection'] },
    { name: 'Data & Endpoint', color: '#00A9BB', subs: ['EDR / XDR','EPP','Email Security (SEG)','BEC / Phishing Protection','DLP','DSPM','Encryption / KMS','Data Classification','Cyber Backup & Recovery','Mobile / MTD','Browser Security','App Control / Whitelisting','Insider Threat'] },
    { name: 'Risk & Compliance', color: '#FEC700', subs: ['GRC Platform','Third-Party / Vendor Risk','Compliance Automation','Privacy & Data Governance','Security Awareness Training','Phishing Simulation','Cyber Insurance Readiness'] },
    { name: 'OT / IoT & Physical', color: '#9b59b6', subs: ['OT / ICS Security','IoT Security','Medical Device Security','OT Network Monitoring','Asset Inventory (OT)','OT Vulnerability Management'] },
  ],
  vendorMap: {
    'CrowdStrike': { primarySub: 'EDR / XDR', secondarySubs: ['ITDR','Threat Hunting','MDR','Pen Testing / BAS'] },
    'SentinelOne': { primarySub: 'EDR / XDR', secondarySubs: ['ITDR','Threat Hunting','MDR'] },
    'Microsoft': { primarySub: 'SSO / Federation', secondarySubs: ['MFA / Passwordless','Directory Services','EDR / XDR','SIEM','SOAR','DLP','Compliance Automation','VM Scanning'] },
    'Microsoft Defender': { primarySub: 'EDR / XDR', secondarySubs: ['VM Scanning','ITDR'] },
    'Microsoft Sentinel': { primarySub: 'SIEM', secondarySubs: ['SOAR','UEBA','Threat Intelligence'] },
    'Microsoft Entra': { primarySub: 'SSO / Federation', secondarySubs: ['MFA / Passwordless','Directory Services','ITDR','PAM'] },
    'Microsoft Intune': { primarySub: 'Mobile / MTD', secondarySubs: ['App Control / Whitelisting'] },
    'MSFT Intune': { primarySub: 'Mobile / MTD', secondarySubs: ['App Control / Whitelisting'] },
    'Okta': { primarySub: 'SSO / Federation', secondarySubs: ['MFA / Passwordless','Directory Services','ITDR'] },
    'Palo Alto': { primarySub: 'NGFW', secondarySubs: ['ZTNA','CSPM','CNAPP','Secure Web Gateway','DNS Security','MDR'] },
    'Prisma Cloud': { primarySub: 'CSPM', secondarySubs: ['CNAPP','CWPP','CIEM','Container / Kubernetes','IaC Security'] },
    'Fortinet': { primarySub: 'NGFW', secondarySubs: ['IDS / IPS','Secure Web Gateway','DNS Security','Remote Access / VPN'] },
    'Zscaler': { primarySub: 'Secure Web Gateway', secondarySubs: ['ZTNA','Remote Access / VPN','DLP','CASB','DNS Security'] },
    'CyberArk': { primarySub: 'PAM', secondarySubs: ['Privileged Remote Access','Secrets Management','ITDR'] },
    'BeyondTrust': { primarySub: 'PAM', secondarySubs: ['Privileged Remote Access','IGA'] },
    'Delinea': { primarySub: 'PAM', secondarySubs: ['Privileged Remote Access','Secrets Management'] },
    'SailPoint': { primarySub: 'IGA', secondarySubs: ['PAM','Directory Services'] },
    'Saviynt': { primarySub: 'IGA', secondarySubs: ['PAM','CIEM'] },
    'Proofpoint': { primarySub: 'Email Security (SEG)', secondarySubs: ['BEC / Phishing Protection','Threat Intelligence','DLP','Security Awareness Training','Phishing Simulation'] },
    'Mimecast': { primarySub: 'Email Security (SEG)', secondarySubs: ['BEC / Phishing Protection','Security Awareness Training','Phishing Simulation'] },
    'Abnormal Security': { primarySub: 'BEC / Phishing Protection', secondarySubs: ['Email Security (SEG)'] },
    'Splunk': { primarySub: 'SIEM', secondarySubs: ['SOAR','UEBA','Data Pipeline / Log Management','Threat Hunting'] },
    'Google SecOps': { primarySub: 'SIEM', secondarySubs: ['SOAR','Threat Intelligence','Digital Risk Protection'] },
    'Google GTI': { primarySub: 'Threat Intelligence', secondarySubs: ['Digital Risk Protection'] },
    'IBM QRadar': { primarySub: 'SIEM', secondarySubs: ['SOAR','UEBA'] },
    'Elastic': { primarySub: 'SIEM', secondarySubs: ['Data Pipeline / Log Management','Threat Hunting'] },
    'Cribl': { primarySub: 'Data Pipeline / Log Management', secondarySubs: ['SIEM'] },
    'Tenable': { primarySub: 'VM Scanning', secondarySubs: ['Attack Surface Management','Cloud Detection & Response'] },
    'Qualys': { primarySub: 'VM Scanning', secondarySubs: ['Attack Surface Management','CSPM'] },
    'Rapid7': { primarySub: 'VM Scanning', secondarySubs: ['Attack Surface Management','MDR','Pen Testing / BAS'] },
    'Wiz': { primarySub: 'CSPM', secondarySubs: ['CNAPP','CIEM','CWPP','DSPM','Cloud Detection & Response'] },
    'Orca': { primarySub: 'CSPM', secondarySubs: ['CNAPP','CIEM','CWPP','DSPM'] },
    'Lacework': { primarySub: 'CSPM', secondarySubs: ['CNAPP','CWPP','Cloud Detection & Response'] },
    'Netskope': { primarySub: 'CASB', secondarySubs: ['Secure Web Gateway','DLP','ZTNA'] },
    'Varonis': { primarySub: 'DSPM', secondarySubs: ['DLP','Data Classification','UEBA'] },
    'Rubrik': { primarySub: 'Cyber Backup & Recovery', secondarySubs: ['DSPM'] },
    'Cohesity': { primarySub: 'Cyber Backup & Recovery', secondarySubs: ['DSPM'] },
    'Veeam': { primarySub: 'Cyber Backup & Recovery', secondarySubs: [] },
    'Arctic Wolf': { primarySub: 'MDR', secondarySubs: ['SIEM','Threat Hunting','VM Scanning'] },
    'Huntress': { primarySub: 'MDR', secondarySubs: ['EDR / XDR','Threat Hunting'] },
    'Red Canary': { primarySub: 'MDR', secondarySubs: ['Threat Hunting','EDR / XDR'] },
    'Expel': { primarySub: 'MDR', secondarySubs: ['SOAR','Threat Hunting'] },
    'Recorded Future': { primarySub: 'Threat Intelligence', secondarySubs: ['Digital Risk Protection','Attack Surface Management'] },
    'Mandiant': { primarySub: 'IR Platform / Retainer', secondarySubs: ['Threat Intelligence','Digital Forensics','MDR'] },
    'Kroll': { primarySub: 'IR Platform / Retainer', secondarySubs: ['Digital Forensics'] },
    'KnowBe4': { primarySub: 'Security Awareness Training', secondarySubs: ['Phishing Simulation'] },
    'Cofense': { primarySub: 'Phishing Simulation', secondarySubs: ['BEC / Phishing Protection'] },
    'Vanta': { primarySub: 'Compliance Automation', secondarySubs: ['Third-Party / Vendor Risk'] },
    'Drata': { primarySub: 'Compliance Automation', secondarySubs: ['Third-Party / Vendor Risk'] },
    'OneTrust': { primarySub: 'Privacy & Data Governance', secondarySubs: ['Compliance Automation','Third-Party / Vendor Risk'] },
    'ServiceNow': { primarySub: 'GRC Platform', secondarySubs: ['Compliance Automation','Third-Party / Vendor Risk'] },
    'BitSight': { primarySub: 'Third-Party / Vendor Risk', secondarySubs: ['Attack Surface Management'] },
    'SecurityScorecard': { primarySub: 'Third-Party / Vendor Risk', secondarySubs: ['Attack Surface Management'] },
    'Claroty': { primarySub: 'OT / ICS Security', secondarySubs: ['IoT Security','Asset Inventory (OT)','OT Network Monitoring'] },
    'Dragos': { primarySub: 'OT / ICS Security', secondarySubs: ['OT Network Monitoring','OT Vulnerability Management'] },
    'Nozomi': { primarySub: 'OT / ICS Security', secondarySubs: ['IoT Security','OT Network Monitoring'] },
    'Armis': { primarySub: 'IoT Security', secondarySubs: ['OT / ICS Security','Asset Inventory (OT)','Medical Device Security'] },
    'Forescout': { primarySub: 'NAC', secondarySubs: ['IoT Security','OT / ICS Security','Asset Inventory (OT)'] },
    'Cisco': { primarySub: 'NGFW', secondarySubs: ['NAC','DNS Security','Remote Access / VPN','MFA / Passwordless','Secure Web Gateway'] },
    'Duo': { primarySub: 'MFA / Passwordless', secondarySubs: ['SSO / Federation'] },
    'Ping Identity': { primarySub: 'SSO / Federation', secondarySubs: ['MFA / Passwordless','Directory Services','CIAM'] },
    'HashiCorp Vault': { primarySub: 'Secrets Management', secondarySubs: ['PAM','Privileged Remote Access'] },
    'Venafi': { primarySub: 'PKI / Cert Management', secondarySubs: [] },
    'Thales': { primarySub: 'Encryption / KMS', secondarySubs: ['PKI / Cert Management'] },
    'Imperva': { primarySub: 'WAF', secondarySubs: ['API Security','DLP'] },
    'Cloudflare': { primarySub: 'WAF', secondarySubs: ['DNS Security','DDoS Protection','ZTNA','API Security','Remote Access / VPN'] },
    'Akamai': { primarySub: 'DDoS Protection', secondarySubs: ['WAF','DNS Security','Secure Web Gateway','Micro-segmentation'] },
    'F5': { primarySub: 'WAF', secondarySubs: ['DDoS Protection','API Security'] },
    'Checkmarx': { primarySub: 'SAST', secondarySubs: ['SCA','API Security'] },
    'Veracode': { primarySub: 'SAST', secondarySubs: ['DAST','SCA'] },
    'Snyk': { primarySub: 'SCA', secondarySubs: ['SAST','Container / Kubernetes','IaC Security','Secrets Scanning'] },
    'Salt Security': { primarySub: 'API Security', secondarySubs: [] },
    'Horizon3': { primarySub: 'Pen Testing / BAS', secondarySubs: ['VM Scanning','Attack Surface Management'] },
    'Pentera': { primarySub: 'Pen Testing / BAS', secondarySubs: ['VM Scanning'] },
    'AttackIQ': { primarySub: 'Pen Testing / BAS', secondarySubs: ['VM Scanning'] },
    'XM Cyber': { primarySub: 'Pen Testing / BAS', secondarySubs: ['Attack Surface Management','VM Scanning'] },
    'Illumio': { primarySub: 'Micro-segmentation', secondarySubs: ['ZTNA'] },
    'Darktrace': { primarySub: 'NDR', secondarySubs: ['UEBA','Threat Hunting','Email Security (SEG)'] },
    'ExtraHop': { primarySub: 'NDR', secondarySubs: ['Threat Hunting'] },
    'Vectra': { primarySub: 'NDR', secondarySubs: ['UEBA','ITDR','Threat Hunting'] },
    'Axonius': { primarySub: 'Asset Inventory (OT)', secondarySubs: ['Attack Surface Management','IoT Security'] },
    'Tanium': { primarySub: 'VM Scanning', secondarySubs: ['EDR / XDR','Attack Surface Management','App Control / Whitelisting'] },
    'BigID': { primarySub: 'Data Classification', secondarySubs: ['DSPM','Privacy & Data Governance'] },
    'Digital Guardian': { primarySub: 'DLP', secondarySubs: ['Insider Threat','Data Classification'] },
    'Forcepoint': { primarySub: 'DLP', secondarySubs: ['Secure Web Gateway','Insider Threat'] },
    'Code42': { primarySub: 'Insider Threat', secondarySubs: ['DLP'] },
    'Dtex': { primarySub: 'Insider Threat', secondarySubs: ['UEBA'] },
    'Teramind': { primarySub: 'Insider Threat', secondarySubs: ['UEBA','DLP'] },
    'Lookout': { primarySub: 'Mobile / MTD', secondarySubs: ['CASB'] },
    'Zimperium': { primarySub: 'Mobile / MTD', secondarySubs: [] },
    'Jamf': { primarySub: 'Mobile / MTD', secondarySubs: ['App Control / Whitelisting'] },
    'ThreatLocker': { primarySub: 'App Control / Whitelisting', secondarySubs: ['Privileged Remote Access'] },
    'Island': { primarySub: 'Browser Security', secondarySubs: ['Secure Web Gateway','DLP'] },
    'Menlo Security': { primarySub: 'Browser Security', secondarySubs: ['Secure Web Gateway'] },
    '1Password': { primarySub: 'Password Manager', secondarySubs: ['Secrets Management'] },
    'LastPass': { primarySub: 'Password Manager', secondarySubs: [] },
    'Keeper': { primarySub: 'Password Manager', secondarySubs: ['Privileged Remote Access'] },
    'Dashlane': { primarySub: 'Password Manager', secondarySubs: [] },
    'DataDog': { primarySub: 'Data Pipeline / Log Management', secondarySubs: ['VM Scanning','Attack Surface Management'] },
    'Sumo Logic': { primarySub: 'Data Pipeline / Log Management', secondarySubs: ['SIEM'] },
    'Workiva': { primarySub: 'GRC Platform', secondarySubs: ['Compliance Automation'] },
    'Archer': { primarySub: 'GRC Platform', secondarySubs: ['Third-Party / Vendor Risk','Compliance Automation'] },
    'LogicGate': { primarySub: 'GRC Platform', secondarySubs: ['Third-Party / Vendor Risk'] },
    'Prevalent': { primarySub: 'Third-Party / Vendor Risk', secondarySubs: [] },
    'Tenex': { primarySub: 'MDR', secondarySubs: ['SIEM','Threat Hunting'] },
    'Sophos': { primarySub: 'EDR / XDR', secondarySubs: ['Email Security (SEG)','Phishing Simulation','Secure Web Gateway'] },
    'Trend Micro': { primarySub: 'EDR / XDR', secondarySubs: ['Email Security (SEG)','CSPM','Container / Kubernetes'] },
    'Check Point': { primarySub: 'NGFW', secondarySubs: ['Email Security (SEG)','ZTNA','Remote Access / VPN'] },
    'Infoblox': { primarySub: 'DNS Security', secondarySubs: ['NAC'] },
    'Cybereason': { primarySub: 'EDR / XDR', secondarySubs: ['MDR','Threat Hunting','ITDR'] },
  }
}

export function resolveVendorMapping(vendorName, existingCategory) {
  if (!vendorName) return { primarySub: existingCategory || 'Unknown', secondarySubs: [] }
  const name = vendorName.trim()
  const exactMatch = SECURITY_FRAMEWORK.vendorMap[name]
  if (exactMatch) return exactMatch
  const fuzzyKey = Object.keys(SECURITY_FRAMEWORK.vendorMap).find(k =>
    name.toLowerCase().includes(k.toLowerCase()) ||
    k.toLowerCase().includes(name.toLowerCase())
  )
  if (fuzzyKey) return SECURITY_FRAMEWORK.vendorMap[fuzzyKey]
  return { primarySub: existingCategory || 'Unknown', secondarySubs: [] }
}